spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:postgresql://postgres:5432/microservices_db?currentSchema=order_schema
spring.datasource.username=order_app
spring.datasource.password=order123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

services.customer.base-url=http://customer-service:8081

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=order-service

spring.cloud.discovery.enabled=true
spring.cloud.loadbalancer.enabled=true