spring.application.name=notification-service
server.port=8083


# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/microservices_db?currentSchema=notification_schema}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:notification_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:notification123}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Consumer
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.consumer.group-id=notification-group

spring.kafka.consumer.auto-offset-reset=earliest


spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


spring.kafka.consumer.properties.spring.json.trusted.packages=com.demo.notification.infrastructure.adapter.messaging.dto,com.demo.notification.model


spring.kafka.consumer.properties.spring.json.value.default.type=com.demo.notification.infrastructure.adapter.messaging.dto.OrderEventDto

# Logging
logging.level.com.demo.notification_service=DEBUG
logging.level.org.springframework.kafka=INFO